defaults:
  - rewards@trainer_class.reward_model: pfn_explore

#  - loss@loss_fn: seq #  auc_weighed_mse
#  - optimizer@optimizer: adamw

epochs: 100 # one cycle is (collect_rollouts, ppo_epochs)

trainer_class:
  _target_: src.l2o.trainer.ppo_trainer.ContinuousPPOTrainer

  buffer:
    _target_: src.l2o.environment.trajectory_buffer.CumulativeEpisodeBuffer
    total_episodes: ${environment.env_class.num_envs}
    max_steps: ${environment.env_class.max_steps}
    obs_dim: ${environment.obs_dim}
    act_dim: ${environment.act_dim}
    device: ${device}

  clip_coef: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  ppo_epochs: 1 # number of epochs over the collected rollouts in the buffer.
  mini_batch_size: 64 # number of samples from the buffer per batch in one PPO step

  callbacks:
    - _target_: src.l2o.trainer.callbacks.mlflow.MLflowCallback
      experiment_name: ${experiment_name}
      run_name: ${run_name}
      mlflow_tracking_uri: Null
      log_system_metrics: False

    - _target_: src.l2o.trainer.callbacks.evaluation.ValidationCallback
      env:
        _target_: src.l2o.environment.sinusoid.VectorizedSinusoidEnv
        num_envs: 256
        max_steps: 50
        device: ${device}