defaults:
  - environment: sinenv
  - model: policy
  - trainer: ppo_trainer
  - _self_



seed: 0

experiment_name: debug # ???
run_name: Null # ???

# change dir
hydra:
  job:
    chdir: True

device: cuda